baseURL = 'https://beyrakin.github.io'
languageCode = 'en-us'
title = "Beyrak's Blog"
theme = 'cactus'


[params]
  description = "Beyrak's Blog"
  author = "Beyrak"
  keywords = ["blog", "beyrak", "beyrakin", "beyrak's blog", "Beyrak Asgarzade"]

# Paper theme
  color = 'gray'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'be7rak'     # twitter.com/YOUR_TWITTER_ID
  github = 'beyrakIn'       # github.com/YOUR_GITHUB_ID
  instagram = 'be7rak' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'https://pbs.twimg.com/profile_images/1580984251368996887/eAMDc48u_400x400.jpg'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Beyrak'
  bio = 'Cyber Security Researcher'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true

# Cactus theme
  colortheme = "dark"

[menu]
    [[menu.main]]
    identifier = 'home'
    name = 'Home Page'
    pre = "<i class='fa fa-heart'>salam</i>"
    url = '/'
